### ISSUE TITLE
Update V14 > V23 upgrade guide after 23.2 release

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#1606]
[V14 > V23 upgrade guide](https://vaadin.com/docs/latest/upgrading/essential-steps) should be updated to reflect changes introduced by the release of V23.2.

**Comment by mshabarov** [comment]
Breaking changes in Flow 23.2:

- [ ] https://github.com/vaadin/platform/issues/3009 : Vite is now used by default for bundling the frontend resources and running the dev server. Thus, if your project has a custom configuration for Webpack in `webpack.config.js`, it should be adapted to the Vite configuration, otherwise, you can still use Webpack through a feature flag.
- [ ] https://github.com/vaadin/hilla/issues/208 : Hilla endpoint classes were moved to Hilla repository from Flow.
- [ ] https://github.com/vaadin/flow/issues/13769 : in non-Spring based Vaadin application, if a custom servlet mapping is used, one should add `/VAADIN/*` to the url patterns of the custom Vaadin servlet.
- [ ] https://github.com/vaadin/flow/pull/13679 : `DevModeGizmo` renamed to `DevTools`. This affects configuration parameter name (`devmodeGizmoEnabled` -> `devToolsEnabled`) and method name in `DeploymentConfiguration`.
- [ ] https://github.com/vaadin/flow/issues/14143 : one can use `RouterLink` without text parameter now. But if you were using `new RouteLink(null, MyView.class)`, you have to replace it with `new RouterLink(MyView.class)`, otherwise you get compilation error.
- [ ] https://github.com/vaadin/flow/pull/14324 : The new license checker is triggered also for production builds and requires an offline license for development in an offline environment.
